[package]
name = "niulai-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["staticlib"]
doctest = false

[dependencies]
passport-core = { path = "../../crates/passport-core" }
passport-platform = { path = "../../crates/passport-platform" }
